### ISSUE TITLE
Change Tagging To `vX.Y.Z`

### ISSUE THREAD

**Issue by korverdev** [rlespinasse/github-slug-action#114]
**Is your feature request related to a problem? Please describe.**
When tagging a specific version of this action within a workflow, you must use the syntax `x.y.z` rather than the standard `vx.y.z` that all official actions make use of.

**Describe the solution you'd like**
Change tagging on releases to include a leading `v`.

**Describe alternatives you've considered**
`N/A`

**Additional context**
`N/A`

**Comment by rlespinasse** [comment]
The official actions use the `v` prefix but this is not the SemVer convention.
The documentation proposes an example using the `v` prefix (https://docs.github.com/en/actions/creating-actions/releasing-and-maintaining-actions#example-developer-process).

The absence of `v` prefix doesn't seem to break anything. @Casey-Kiewit Have you a use case impacted because of this missing prefix?

Since v3 and v4 branches start without the prefix, I think we can continue those releases without any change. Starting with `v5` branch, the new release will take into account the `v` prefix and so, will be more close to the current major tagging system (which uses the `v` prefix): `v3`, and `v4`)

**Comment by korverdev** [comment]
@rlespinasse That makes sense to me. Appreciate you weighing in.

This isn't causing any issues, so there's no huge rush to change this, but the absence of the `v` seemed somewhat unexpected and makes code reviews on those files a little trickier.

**Comment by nicolas2mey** [comment]
Not breaking anything on my side but effectively there is a convention. 
Not for "release following semver" but "git tags following semver" 
https://semver.org/spec/v1.0.0.html#spec-item-11 specifically here

But no real big deals

**Comment by rlespinasse** [comment]
@nicolas2mey nice finding, thanks you

**Comment by rlespinasse** [comment]
v1 of semver speak of a `SemVerTag` format, but not v2 of semver.
But the content aka `you can use v* prefix on git tag` remains https://semver.org/spec/v2.0.0.html#is-v123-a-semantic-version

**Comment by rlespinasse** [comment]
Finally, the 3.7.0 and 4.3.0 versions will be tagged with the `v` prefix. I experiment on my other smaller projects and the migration is more straightforward than I imagine.
