### ISSUE TITLE
GITHUB_SHA_SHORT Not Working in V4

### ISSUE THREAD

**Issue by jmwyson** [rlespinasse/github-slug-action#88]
**Describe the bug**
GITHUB_SHA_SHORT variable is not being populated in v4 for the action.

**To Reproduce**
Add rlespinasse/github-slug-action@v4 action
Try to access env.GITHUB_SHA_SHORT

**Expected behavior**
GITHUB_SHA_SHORT contains the short SHA

**Additional context**
I replaced rlespinasse/github-slug-action@v4 with rlespinasse/github-slug-action@3.6.0 and the variable works.

**Comment by rlespinasse** [comment]
This bug occurs when this action is used before or without `actions/checkout@v3`

1. GITHUB_SHA_SHORT is filled
   ```yaml
   - uses: actions/checkout@v3
   - uses: rlespinasse/github-slug-action@v4
   ```
1. GITHUB_SHA_SHORT isn't filled
   ```yaml
   - uses: rlespinasse/github-slug-action@v4
   - uses: actions/checkout@v3
   ```
1. GITHUB_SHA_SHORT isn't filled
   ```yaml
   - uses: rlespinasse/github-slug-action@v4
   ```

`rlespinasse/github-slug-action@v3` is not impacted because the `v3` version does not checkout reference (and so does not need a git repository).

Two possibilities to fix that

- 1️⃣  Document it as a feature, but this will make `actions/checkout` action mandatory for `rlespinasse/github-slug-action@v4` (and this can be explained as one of the breaking changes of the `v4` branch)
- 2️⃣ Make the `rlespinasse/shortify-git-revision` action support the `shortify` of the git revision even in case of a missing git repository (and document this behavior in both actions)

**Comment by rlespinasse** [comment]
We will go with the solution 2️⃣
