### ISSUE TITLE
Error: The input 'lenght' is mandatory with 'short-on-error' set to 'true' in v4.2.0

### ISSUE THREAD

**Issue by apottere** [rlespinasse/github-slug-action#95]
**Describe the bug**
Workflow including this action fails with:
```
Error: The input 'lenght' is mandatory with 'short-on-error' set to 'true'
Error: Process completed with exit code 1.
```

**To Reproduce**
```
        steps:
            - name: Inject GitHub Short Names
              uses: rlespinasse/github-slug-action@v4.x
```

**Expected behavior**
Workflow does not fail.

**Additional context**
Note that `lenght` is misspelled in the error message, which might be an indicator of where the issue stems from?

**Comment by apottere** [comment]
I just confirmed pinning to `rlespinasse/github-slug-action@4.1.0` resolves the issue, so it does seem to be an error in `4.2.0`

**Comment by rlespinasse** [comment]
This bug occurs when you use this action in v4.2.0 without checkout sources (same impact as #88)
But the resolution of #92 has re-introduced the bug in a different way (not caught by the test suite obviously 😢).
The `empty` short-length input was to keep the `4.0.0` behavior.
We need to improve the behavior in case of missing git repository.

Additional bug - you found a typo in the error message.

TIPS: You can use `rlespinasse/github-slug-action@v4` instead of `rlespinasse/github-slug-action@v4.x` to use tagged version instead of branch content (this will not resolve the issue)

**Comment by apottere** [comment]
Thanks for the quick fix - and for the tip about `v4` vs `v4.x`!  Completely missed one was a branch and the other a tag.
